title: Bhanut Sriplakich
logo: /assets/img/profile_pic_1.png
description: Join me on this exciting journey as I build more ML and AI-powered projects!
show_downloads: false
theme: jekyll-theme-minimal